# Generated by Django 5.2.17 on 2026-09-01 13:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('contact_number', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=80, verbose_name='TIN')),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('category', models.CharField(choices=[('MATERIAL', 'Material'), ('LAMINATE', 'Laminate'), ('BOARD', 'Board / Substrate'), ('INK', 'Ink'), ('ELECTRICITY', 'Electricity'), ('MANPOWER', 'Manpower'), ('MACHINE', 'Machine'), ('FINISHING', 'Finishing / Consumable'), ('INSTALLATION', 'Installation'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='MATERIAL', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('unit', models.CharField(choices=[('SQFT', 'per sq.ft.'), ('PIECE', 'per piece'), ('HOUR', 'per hour'), ('MINUTE', 'per minute'), ('JOB', 'per job / setup'), ('UNIT', 'per unit')], default='SQFT', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_inclusive', models.BooleanField(default=True)),
                ('purchase_description', models.CharField(blank=True, max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('pricing_type', models.CharField(choices=[('AREA', 'Area-based'), ('PIECE', 'Piece-based')], max_length=10)),
                ('walk_in_rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('tie_up_rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('buffer_percent', models.DecimalField(decimal_places=2, default=5, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=180)),
                ('customer_type', models.CharField(choices=[('WALK_IN', 'Walk-In'), ('TIE_UP', 'Tie-Up')], default='WALK_IN', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=12)),
                ('quotation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('validity_days', models.PositiveIntegerField(default=15)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('FT', 'feet'), ('IN', 'inches')], default='FT', max_length=2)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('selling_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='core.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=30)),
                ('basis', models.CharField(max_length=40)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('usage_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('computed_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown', to='core.quotationitem')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis', models.CharField(choices=[('AREA', 'Area × quantity'), ('PIECE', 'Quantity'), ('FIXED', 'Fixed per job')], max_length=10)),
                ('usage_quantity', models.DecimalField(decimal_places=4, default=1, help_text='Amount of this cost item used for each sq.ft., piece, or job.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_components', to='core.costitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_components', to='core.product')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'cost_item', 'basis'), name='unique_product_cost_basis')],
            },
        ),
    ]
