# Generated by Django 5.2.17 on 2026-09-01 13:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItemExtraCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis', models.CharField(choices=[('AREA', 'Area × quantity'), ('PIECE', 'Quantity'), ('FIXED', 'Fixed per job')], default='FIXED', max_length=10)),
                ('usage_quantity', models.DecimalField(decimal_places=4, default=1, help_text='Example: enter 4 for four eyelets, or 3 for three installation hours.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_extra_costs', to='core.costitem')),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_costs', to='core.quotationitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
