# Generated by Django 5.2.17 on 2026-09-29 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reusable_quotation_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(choices=[('FT', 'feet (ft)'), ('IN', 'inches (in)'), ('MM', 'millimeters (mm)'), ('CM', 'centimeters (cm)'), ('M', 'meters (m)')], default='FT', max_length=2),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
